# -*- coding: utf-8 -*-
"""train_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maLJboRp9LTvhNytBbwaSsnbdVVUxbjv
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
data={'text':['hello section B','win the lottery','congratulation'],'label':['not spam','spam','spam'],}
df=pd.DataFrame(data)
df
X = df['text']
Y = df['label']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25,random_state=42)
vectorizer=CountVectorizer()
X_train_counts=vectorizer.fit_transform(X_train)
X_test_counts=vectorizer.transform(X_test)
model = MultinomialNB()
model.fit(X_train_counts, Y_train)
Y_pred = model.predict(X_test_counts)

accuracy = accuracy_score(Y_test, Y_pred)

